config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :categories

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'sign_up' }

  get 'dashboard', to: 'home#dashboard'

  resources :tasks, only: [ :create, :edit, :destroy, :update ] do
    collection do
      post 'create2'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  title      :string
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, :user, presence: true
  validates :title, length: { maximum: 30 }
  validate :unique_category, on: :create # unique category per user

  extend FriendlyId
  friendly_id :title, use: :slugged

  private
  def unique_category
    results = user.categories.where(title: title)
    errors.add(:title, " already exists") if results.present?
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category

  has_many :users, through: :category

  validates :title, :description, :deadline, :category_id, presence: true
  validates :description, length: { minimum: 5, maximum: 35 }
  validate :not_past_date, on: :create
  validate :unique_task_per_category, on: [ :create, :create2 ]

  enum status: {
    in_progress: 0,
    completed: 1
  }

  scope :in_progress, -> { where(status: "in_progress") }
  scope :completed, -> { where(status: "completed") }
  scope :less_than_today, -> { where("deadline < ?", DateTime.current.beginning_of_day) }

  private

  def not_past_date
    return if deadline.nil? || deadline.today?

    if deadline.past?
      return errors.add(:deadline, "must be valid")
    end
  end

  def unique_task_per_category
    results = category.tasks.where(title: title)
    return errors.add(:title, " already exists, not unique") if results.present?
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  has_many :categories, dependent: :destroy
  has_many :tasks, through: :categories

  validates :first_name, :last_name, presence: true

  enum language: {
    English: "English",
    Tagalog: "Tagalog"
  }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    
    before_action :set_page_defaults
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :set_language
    
    # devise redirect path after logging in
    def after_sign_in_path_for(resource)
        dashboard_path
    end

    def set_page_defaults
        @page_title = t('page_title')
    end

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :language])
    end

    def set_language
        if current_user
            current_user.language == 'English' ? I18n.locale = :en : I18n.locale = :tl
        else
            I18n.locale = :en
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [ :show, :edit, :update, :destroy ]

  def index
    flash[:task_error] = nil
    @categories = current_user.categories.order(created_at: :desc)
    @page_title = "All Categories"
  end

  def show
    flash[:task_error] = nil
    @page_title = @category.title    
  end

  def new
    @category = current_user.categories.build
  end

  def create
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to categories_path, notice: I18n.t('controllers.categories.added_category')
    else
      @categories = current_user.categories.order(created_at: :desc)
      flash[:task_error] = @category.errors.full_messages
      render 'categories/index'
    end
  end

  def edit
  end

  def update
    title = @category.title
    if @category.update(category_params)
      redirect_to @category, notice: I18n.t('controllers.categories.updated_category')
    else
      flash[:task_error] = @category.errors.full_messages
      @title = title
      render :show
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, notice: I18n.t('controllers.categories.deleted_category')
  end

  private
  def set_category
    @category = current_user.categories.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [ :dashboard ]
  
  def index
  end

  def dashboard
    @tasks = current_user.tasks.in_progress
    @completed_tasks = current_user.tasks.completed
    @total_tasks = current_user.tasks
    @overdue = current_user.tasks.less_than_today.in_progress
    @today = I18n.l(DateTime.current.beginning_of_day, format: '%-d %B %Y, %A')
    @page_title = "Welcome, #{current_user.first_name}"
  end

  private
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :edit, :destroy ]
  before_action :set_category, only: [ :create, :update, :destroy, :create2 ]

  def create
    flash[:task_error] = nil
    @task = @category.tasks.create(task_params)

    if @task.save
      redirect_to categories_path, notice: I18n.t('controllers.tasks.added_task')
    else
      flash[:task_error] = @task.errors.full_messages

      render '/categories/show'
    end
  end

  def create2
    flash[:task_error] = nil
    @task = @category.tasks.create(task_params)

    if @task.save
      redirect_to category_path(@category), notice: I18n.t('controllers.tasks.added_task')
    else
      flash[:task_error] = @task.errors.full_messages

      render 'categories/show'
    end
  end

  def update
    flash[:task_error] = nil
    @task = @category.tasks.find(params[:id])

    if @task.update(task_params) 
      redirect_to category_path(@category), notice: I18n.t('controllers.tasks.updated_task')
    else
      flash[:task_error] = @task.errors.full_messages
      render 'categories/show/'
    end
  end

  def destroy
    @task.destroy
    redirect_to category_path(@category), notice: I18n.t('controllers.tasks.deleted_task')
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def set_category
    @category = Category.find(params[:category_id])   
  end

  def task_params
    params.require(:task).permit(:title, :description, :deadline, :status, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/edit.html.erb
<h1 class="text-center mt-5">Edit a post</h1>

<%= form_with model: @category do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <%= form.submit %>
<% end %>

<%= link_to "go back", @category %>

app/views/categories/index.html.erb
<% if flash[:task_error] %>
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <ul class="task-error">
          <% flash[:task_error].each do |error| %>
            <li class="text-danger"><%= error %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<h1 class="<%= 'mt-4' if flash[:task_error].nil? %> text-center mb-4 dark-font display-4 font-weight-bold"><%= t('phrases.index_categories') %></h1>

<div class="bg-gray">
  <div class="container">
    <div class="row pb-4">
      <% @categories.each do |category| %>
        <div class="col-sm-3 pt-4">
          <div class="card">
            <div class="card-body d-flex flex-column justify-content-center align-items-center">
              <h4 class="card-title text-center"><%= link_to category.title, category_path(category), class: "category-link"  %></h4>

              <% if category.tasks.count > 0 %>
                <p class="card-text text-center"><%= t('phrases.completed_tasks') %>: <%= category.tasks.where(status: 'completed').count %> of <%= category.tasks.count %></p>

                <p class="card-text text-center"><button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#exampleModalScrollable<%= category.id %>"><%= t('phrases.add_a_task') %></button></p>
              <% else %>
                <p class="card-text text-center"><%= t('phrases.no_tasks') %></p>
                <p class="card-text text-center"><button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#exampleModalScrollable<%= category.id %>"><%= t('phrases.add_a_task') %></button></p>
              <% end %>

              <p class="card-text text-center"><%= link_to category, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger" do %><i class="fa fa-trash"></i> <%= t('phrases.delete') %><% end %></p>
            </div>
          </div>
        </div>

        <!-- add task Modal -->
        <div class="modal fade" id="exampleModalScrollable<%= category.id %>" tabindex="-1" role="dialog"
                    aria-labelledby="exampleModalScrollableTitle<%= category.id %>" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalScrollableTitle<%= category.id %>"><%= t('phrases.add_a_task_for') %> <%= category.title %></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= form_with scope: :task, model: category.tasks.build , local: true do |form| %>
                  <%= hidden_field_tag :category_id, category.id %>

                  <div class="form-group">
                    <%= form.text_field :title, placeholder: "Title", class: "form-control" %>
                  </div>

                  <div class="form-group">
                    <p><%= form.text_area :description, placeholder: "Description", class: "form-control", rows: 10 %></p>
                  </div>

                  <div class="form-group">
                    <p><%= form.date_field :deadline, class: "form-control" %></p>
                  </div>

                  <div class="form-group">
                    <p><%= form.select :status, Task.statuses.keys, {}, { :class => 'form-control' } %></p>
                  </div>

                  <%= form.submit t('phrases.create_task'), class: "btn btn-outline-success w-100" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
         <!-- add task modal -->
      <% end %> <!-- categories loop -->

      <div class="col-sm-3 d-flex align-items-center mt-4">
        <button type="button" class="btn btn-outline-light w-100" data-toggle="modal" data-target="#exampleModalScrollable"><%= t('dashboard.new_category_btn') %></button>
      </div>

      <!-- create category Modal -->
      <div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog"
                aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title devise-headings" id="exampleModalScrollableTitle"><%= t('phrases.add_a_category') %></h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="modal-body">
              <% if flash[:task_error] %>
                <ul>
                  <% flash[:task_error].each do |error| %>
                    <li class="text-danger"><%= error %></li>
                  <% end %>
                </ul>
              <% end %>

              <%= form_with scope: :category, model: @categories.build do |form| %>
                <div class="form-group">
                  <%= form.label :title, class: "devise-headings" %>
                  <%= form.text_field :title, class: "form-control" %>
                </div>

                <%= form.submit t('phrases.create_category'), class: "btn btn-outline-success w-100" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
       <!-- create category modal -->
    </div>
     <!-- row -->
  </div>
   <!-- container -->
</div>
 <!-- bg-green -->

app/views/categories/new.html.erb
<h1 class="text-center mt-5">Create a post</h1>

<%= form_with model: @category do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <%= form.submit %>
<% end %>

<%= link_to "go back", categories_path %>

app/views/categories/show.html.erb
<% if flash[:task_error] %>
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <ul class="task-error">
          <% flash[:task_error].each do |error| %>
            <li class="text-danger"><%= error %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<p class="text-center">
  <button type="button" class="btn btn-link mb-0 show-button" data-toggle="modal" data-target="#exampleModalScrollable<%= @category.id %>">
    <h1 class="<%= 'mt-4' if flash[:task_error].nil? %> display-4 font-weight-bold"><%= @title ? @title : @category.title %></h1>
  </button>
</p>

<p class="text-center category-p"><%= t('phrases.created') %>: <%= I18n.l(@category.created_at, format: "%B %-d, %Y") %> | <%= @category.tasks.count > 1 ? t('phrases.capital_tasks') : t('phrases.capital_task') %>: <%= @category.tasks.count %> | <%= t('phrases.capital_ongoing') %>: <%= @category.tasks.in_progress.count %> | <%= t('phrases.capital_completed') %>: <%= @category.tasks.where(status: 'completed').count > 0 ? (((@category.tasks.where(status: 'completed').count).to_f / (@category.tasks.count).to_f) * 100).ceil : 0 %>%</p>

<!-- category edit modal -->
<div class="modal fade" id="exampleModalScrollable<%= @category.id %>" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalScrollableTitle<%= @category.id %>" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle<%= @category.id %>"><%= t('phrases.edit') %> <%= @category.title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with model: @category do |form| %>
          <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, class: "form-control" %>
          </div>

          <%= form.submit class: "btn btn-outline-success w-100" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- end modal -->

<p class="text-center show-options">
  <%= link_to categories_path, class: "edit-category" do %>
    <i class="fa fa-arrow-left"></i> <%= t('phrases.go_back') %>
  <% end %> | <%= link_to @category, method: :delete, data: { confirm: 'Are you sure?' }, class: "edit-category" do %><i class="fa fa-trash"></i> <%= t('phrases.delete') %><% end %>
</p>

<% if @category.tasks.count > 0 %>
  <!-- in-progress row -->
  <% if @category.tasks.in_progress.count > 0 %>
    <!-- heading -->
    <div class="bg-gray py-2">
      <h4 class="text-center font-white"><%= t('phrases.on_going_tasks') %></h4>
    </div>

    <!-- table -->
    <div class="container mt-4">
      <table class="table table-fixed">
        <thead>
          <tr>
            <th scope="col"><%= t('table.title') %></th>
            <th scope="col"><%= t('table.description') %></th>
            <th scope="col"><%= t('table.deadline') %></th>
            <th scope="col"><%= t('table.status') %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @category.tasks.in_progress.order(deadline: :asc).each do |c| %>
            <tr>
              <th scope="row"><%= c.title %></th>
              <td><%= c.description %></td>
              <th scope="row"><span class="<%= 'text-danger' if c.deadline.beginning_of_day == DateTime.current.beginning_of_day %>"><%= c.deadline.beginning_of_day == DateTime.current.beginning_of_day ? "Due today!" : I18n.l(c.deadline, format: "%B %-d, %Y") %></span></th>
              
              <th scope="row">
                <% if c.status == 'completed' %>
                  <span class="text-success"><%= c.status.capitalize() %></span>
                <% else %>
                  <span class="text-warning"><%= c.status.sub('_', ' ').capitalize() %></span>
                <% end %>
              </th>
              <td>
                <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModalScrollable3<%= c.id %>"><i class="fa fa-edit"></i> <%= t('phrases.edit') %></button>

                <%= link_to task_path(c, :category_id => c.category_id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" do %><i class="fa fa-trash"></i> <%= t('phrases.delete') %><% end %>

                <!-- task edit Modal -->
                <div class="modal fade" id="exampleModalScrollable3<%= c.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle3<%= c.id %>" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalScrollableTitle3<%= c.id %>"><%= t('phrases.edit_task') %></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <%= form_with scope: :task, model: c, local: true do |form| %>
                          <%= hidden_field_tag :category_id, c.category_id %>

                          <div class="form-group">
                            <%= form.text_field :title, placeholder: "Title", class: "form-control" %>
                          </div>

                          <div class="form-group">
                            <p><%= form.text_area :description, placeholder: "Description", class: "form-control", rows: 10 %></p>
                          </div>

                          <div class="form-group">
                            <p><%= form.date_field :deadline, class: "form-control" %></p>
                          </div>

                          <div class="form-group">
                            <p><%= form.select :status, Task.statuses.keys, {}, { :class => 'form-control' } %></p>
                          </div>

                          <%= form.submit t('phrases.edit'), class: "btn btn-outline-success w-100" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- end modal -->
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>

  <!-- completed row -->
  <% if @category.tasks.completed.count > 0 %>
    <!-- heading -->
    <div class="bg-dark py-2">
      <h4 class="text-center font-white"><%= t('phrases.capital_completed') %></h4>
    </div>

    <!-- table -->
    <div class="container mt-4">
      <table class="table table-fixed">
        <thead>
          <tr>
            <th scope="col"><%= t('table.title') %></th>
            <th scope="col"><%= t('table.description') %></th>
            <th scope="col"><%= t('table.deadline') %></th>
            <th scope="col"><%= t('table.status') %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @category.tasks.completed.order(updated_at: :desc).each do |c| %>
            <tr>
              <th scope="row"><%= c.title %></th>
              <td><%= c.description %></td>
              <th scope="row"><%= I18n.l(c.deadline, format: "%B %-d, %Y") %></th>  
              <th scope="row">
                <% if c.status == 'completed' %>
                  <span class="text-success"><%= c.status.capitalize() %></span>
                <% else %>
                  <span class="text-warning"><%= c.status.capitalize() %></span>
                <% end %>
              </th>
              <td>
                <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModalScrollable3<%= c.id %>"><i class="fa fa-edit"></i> <%= t('phrases.edit') %></button>

                <%= link_to task_path(c, :category_id => c.category_id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" do %><i class="fa fa-trash"></i> <%= t('phrases.delete') %><% end %>

                <!-- task edit Modal -->
                <div class="modal fade" id="exampleModalScrollable3<%= c.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle3<%= c.id %>" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalScrollableTitle3<%= c.id %>"><%= t('phrases.edit_task') %></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <%= form_with scope: :task, model: c, local: true do |form| %>
                          <%= hidden_field_tag :category_id, c.category_id %>

                          <div class="form-group">
                            <%= form.text_field :title, placeholder: "Title", class: "form-control" %>
                          </div>

                          <div class="form-group">
                            <p><%= form.text_area :description, placeholder: "Description", class: "form-control", rows: 10 %></p>
                          </div>

                          <div class="form-group">
                            <p><%= form.date_field :deadline, class: "form-control" %></p>
                          </div>

                          <div class="form-group">
                            <p><%= form.select :status, Task.statuses.keys, {}, { :class => 'form-control' } %></p>
                          </div>

                          <%= form.submit t('phrases.edit'), class: "btn btn-outline-success w-100" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- end modal -->
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>

  <!-- add task button -->
  <p class="card-text text-center mb-0"><button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModalScrollable9"><%= t('phrases.create_task') %></button></p>

  <!-- empty task -->
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <%= image_tag("Ice cream seller-cuate.png", :alt => "No tasks available", class: "w-100") %>
        <p class="card-text text-center"><button type="button" class="btn btn-dark" data-toggle="modal" data-target="#exampleModalScrollable9"><%= t('phrases.create_task') %></button></p>
      </div>
    </div>
  </div>
<% end %>

<!-- add task Modal -->
<div class="modal fade" id="exampleModalScrollable9" tabindex="-1" role="dialog"
            aria-labelledby="exampleModalScrollableTitle9" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle5"><%= t('phrases.add_task') %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <% if flash[:task_error] %>
          <ul>
            <% flash[:task_error].each do |error| %>
              <li class="text-danger"><%= error %></li>
            <% end %>
          </ul>
        <% end %>

        <%= form_with scope: :task, model: @category.tasks.build, url: '/tasks/create2', method: :post do |form| %>
          <%#= form_with scope: :task, model: @category.tasks.build, local: true do |form| %>
            <%= hidden_field_tag :category_id, @category.id %>

            <div class="form-group">
              <%= form.text_field :title, placeholder: "Title", class: "form-control" %>
            </div>

            <div class="form-group">
              <p><%= form.text_area :description, placeholder: "Description", class: "form-control", rows: 10 %></p>
            </div>

            <div class="form-group">
              <p><%= form.date_field :deadline, class: "form-control" %></p>
            </div>

            <div class="form-group">
              <p><%= form.select :status, Task.statuses.keys, {}, { :class => 'form-control' } %></p>
            </div>

            <%= form.submit t('phrases.create_task'), class: "btn btn-outline-success w-100" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<br />

app/views/home/index.html.erb
<% content_for :title do %>
  <title>Welcome</title>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 d-flex flex-column justify-content-center align-items-center">
      <h1 class="font-primary primary-h1 text-center mb-3"><%= t('home_page.heading') %></h1>
      <h5 class="font-primary text-center mb-3 primary-p"><%= t('home_page.p_1') %></h5>
    </div>
    <div class="col-md-6">
      <%= image_tag("Online world-bro.png", :alt => "Organize your life", class: "w-100") %>
    </div>
  </div>
  <p class="text-center">
    <%= link_to t('home_page.cta'), new_user_registration_path, class: "btn btn-primary btn-lg main-btn mb-4" %>
  </p>
</div>

<div class="bg-white content-wrap">
  <div class="container">
    <div class="row py-5">
      <div class="col-md-4">
        <p class="text-center"><i style="font-size: 61px;" class="fa fa-address-card"></i></p>
        <h3 class="mb-3 three-col-heading text-center"><%= t('home_page.h2_headings.first') %></h3>

      <p class="font-light-gray text-center col-p"><%= t('home_page.landing_page_p.first') %></p>
    </div>

    <div class="col-md-4">
      <p class="text-center"><i style="font-size: 61px;" class="fa fa-list"></i></p>
      <h3 class="mb-3 three-col-heading text-center"><%= t('home_page.h2_headings.second') %></h3>

      <p class="font-light-gray text-center col-p"><%= t('home_page.landing_page_p.second') %></p>
    </div>

    <div class="col-md-4">
      <p class="text-center"><i style="font-size: 61px;" class="fa fa-heartbeat"></i></p>
      <h3 class="mb-3 three-col-heading text-center"><%= t('home_page.h2_headings.third') %></h3>

      <p class="font-light-gray text-center col-p"><%= t('home_page.landing_page_p.third') %></p>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- google fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navigation' %>
    <div class="container">
      <%= render 'partials/messages' %>
    </div>
    <%= yield %>
    <%#= render 'partials/footer' %>
  </body>
</html>

app/views/tasks/show.html.erb
<% content_for :title do %>
  <title><%= @task.title %></title>
<% end %>

<h1><%= @task.title %></h1>
<p><%= @task.description %></p>
<p><%= @task.deadline %></p>

<%= link_to 'Destroy', task_path(@task), method: :delete, data: { confirm: 'Are you sure?' } %>